#define FOR(i,a,b) for(int i = (a) ; i <= (b) ; i++ )
#define FOD(i,a,b) for(int i = (a) ; i >= (b) ; i-- )
#define REP(i,n) for(int i = 0 ; i < (n) ; i++ )
#define TIME (1.0 * clock() / CLOCKS_PER_SEC )
#define LOG(x)  Serial.println((x))